### ISSUE TITLE
Ubuntu snap is missing permission to access camera

### ISSUE THREAD

**Issue by zbynekwinkler** [paroj/pose_calib#2]
The ubuntu snap is not working for me. It is missing permission to access the camera.

```
$ posecalib
falling back to /snap/posecalib/5/bin/data/calib_config.yml
VIDEOIO ERROR: V4L: can't open camera by index 0
Traceback (most recent call last):
  File "/snap/posecalib/5/bin/pose_calib.py", line 144, in <module>
    main()
  File "/snap/posecalib/5/bin/pose_calib.py", line 83, in main
    cap = UVCVideoCapture(cfg)
  File "/snap/posecalib/5/bin/pose_calib.py", line 41, in __init__
    assert self.cap.isOpened()
AssertionError
```
```
$ snap connections posecalib
Interface  Plug              Slot     Notes
camera     posecalib:camera  -        -
home       posecalib:home    :home    -
opengl     posecalib:opengl  :opengl  -
x11        posecalib:x11     :x11     -
```

After running: `sudo snap connect posecalib:camera :camera` I can actually use the tool.

**Comment by paroj** [comment]
thanks, updated the store description accordingly
